name: Zip Files

on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: ACS BMAP GRAPHICS HIRES MODELS PATCHES SOUNDS SPRITES SRC Textures actors brightmaps zscript ANIMDEFS CVARINFO DECALDEF DECORATE DetailedCredits.txt Fontdefs.txt GLDEFS KEYCONF.txt LOADACS.txt MBlur.f MENUDEF.txt PDAMONST PDAWEAP PDAWEAPT SBARINFO.txt SNDINFO SNDINFO.PDA.txt SNDINFO.Terrain SNDINFO.Vehicles TEXTCOLO.txt Textures.txt TitleMap ZSCRIPT.zc doomdefs.bm doommonsters.bm doomwalls.bm gameinfo.txt language.enu modeldef.txt terrain.wad titlemap.wad trnslate.txt xhairs.wad zmapinfo.txt
          dest: Project_Brutality.pk3
